DROP TABLE IF EXISTS user;

CREATE TABLE user(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY
    username TEXT UNIQUE NOT NULL
    email TEXT UNIQUE NOT NULL 
    password TEXT NOT NULL
);

